---

- name: Copy kibana rpm file
  copy:
    src: "{{ dists }}/kibana-7.5.1-x86_64.rpm"
    dest: /tmp/kibana-7.5.1-x86_64.rpm
    mode: 0755

- name: Install kibana rpms
  yum:
    name: "/tmp/kibana-7.5.1-x86_64.rpm"

- name: Remove kibana rpm file
  file: 
    path: /tmp/kibana-7.5.1-x86_64.rpm
    state: absent

- name: Copy templated kibana.yml
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: root
    group: root
    mode: 0644

- name: Start and enable kibana service
  service:
    name: kibana
    state: restarted
    enabled: true

